{"record_format_version": 3, "code": "\ndocker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev /opt/conda/envs/pydev/bin/python {scripts}/validation_error_rates.py --input {input} --stats-output {output[0]} --plot-output {output[1]}\n        ", "rule": "validation_error_analysis", "input": ["output/C4H6O3_lipinski_results_with_fragments.csv"], "log": [], "params": [], "shellcmd": "\ndocker run --rm --user $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace pydev /opt/conda/envs/pydev/bin/python scripts/validation_error_rates.py --input output/C4H6O3_lipinski_results_with_fragments.csv --stats-output output/C4H6O3_validation_error_stats.csv --plot-output output/C4H6O3_validation_error_visualization.png\n        ", "incomplete": false, "starttime": 1734178283.494971, "endtime": 1734178285.0020087, "job_hash": 8731551125335, "conda_env": null, "container_img_url": null, "input_checksums": {"output/C4H6O3_lipinski_results_with_fragments.csv": "2390db3dec9d2ba35fa9f3aaf5e2c69c4381f568b3e70b90bc1ec64167481bc7"}}